ChuckNorris.Web/Controllers/BioController.cs
using Microsoft.AspNetCore.Mvc;

namespace ChuckNorris.Web.Controllers
{
    public class BioController:Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ChuckNorris.Web/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace ChuckNorris.Web.Controllers
{
    public class ContactController:Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ChuckNorris.Web/Controllers/FactsController.cs
using Microsoft.AspNetCore.Mvc;

namespace ChuckNorris.Web.Controllers
{
    public class FactsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ChuckNorris.Web/Controllers/FavoritesController.cs
using Microsoft.AspNetCore.Mvc;

namespace ChuckNorris.Web.Controllers
{
    public class FavoritesController:Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ChuckNorris.Web/Controllers/OfflineController.cs
using Microsoft.AspNetCore.Mvc;

namespace ChuckNorris.Web.Controllers
{
    public class OfflineController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ChuckNorris.Web/Controllers/SubmissionsController.cs
using Microsoft.AspNetCore.Mvc;

namespace ChuckNorris.Web.Controllers
{
    public class SubmissionsController:Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ChuckNorris.Web/Views/Bio/Index.cshtml
@{
    ViewBag.Title = "Bio";
    Layout = "_Layout";
}

@section Styles {

    <link href="~/css/bio.min.css" rel="stylesheet" asp-append-version="false"/>
}

@section Scripts{
    <script src="~/js/bio.min.js" asp-append-version="false" defer></script>
}

<h1>@ViewBag.Title</h1>

<img id="cartoon-chuck" src="~/images/chuck-norris-cartoon.png" alt="Chuck Norris Img"/>
<div>
    <a class="chuck-link" asp-action="Movies">Known for</a>
</div>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec elit mauris, tincidunt a augue quis, elementum luctus magna. Integer egestas ipsum vel condimentum finibus. Pellentesque dui sem, imperdiet vel orci ut, ultrices viverra velit. Aliquam eu neque augue. In quam massa, ornare ut dui a, sollicitudin maximus ipsum. Fusce at rutrum nisl, nec fringilla dolor. In pharetra gravida metus vitae dignissim.</p>
<p>Pellentesque viverra ex sed tempus scelerisque. Phasellus vel volutpat tellus. Sed faucibus turpis lorem, nec maximus dolor suscipit non. Curabitur in imperdiet nunc. Nam cursus purus massa. Cras fermentum nulla ut augue tempus convallis. Phasellus pulvinar non quam id efficitur. Aliquam erat volutpat. Proin mi metus, dapibus a velit id, suscipit dignissim elit. Fusce tellus urna, luctus vestibulum nisi vel, fermentum gravida orci. Sed vel erat id purus consectetur convallis eu sed augue. Integer consequat, leo hendrerit gravida bibendum, eros magna finibus urna, eu hendrerit nunc tellus a metus. Suspendisse aliquam justo at vestibulum pretium. Ut ullamcorper sit amet risus eu facilisis. Donec vestibulum, ante quis vestibulum pellentesque, sapien magna tristique nunc, a tincidunt augue ipsum ac dolor.</p>
<p>Curabitur tristique tortor est, vel viverra leo rhoncus quis. Aenean dolor lorem, posuere at scelerisque vel, consequat ut purus. Ut facilisis urna quis felis semper interdum. Donec urna risus, suscipit sed enim vitae, posuere molestie risus. Vivamus mattis eu elit at finibus. Ut sit amet lacinia dui. Nulla facilisi. Suspendisse porttitor commodo suscipit. Nullam ac nisi sem. Donec a urna nec turpis sodales aliquet vel vel velit. Phasellus eu dignissim mi, quis semper mauris. Sed nisl erat, tempor at laoreet sit amet, facilisis in urna.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec elit mauris, tincidunt a augue quis, elementum luctus magna. Integer egestas ipsum vel condimentum finibus. Pellentesque dui sem, imperdiet vel orci ut, ultrices viverra velit. Aliquam eu neque augue. In quam massa, ornare ut dui a, sollicitudin maximus ipsum. Fusce at rutrum nisl, nec fringilla dolor. In pharetra gravida metus vitae dignissim.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec elit mauris, tincidunt a augue quis, elementum luctus magna. Integer egestas ipsum vel condimentum finibus. Pellentesque dui sem, imperdiet vel orci ut, ultrices viverra velit. Aliquam eu neque augue. In quam massa, ornare ut dui a, sollicitudin maximus ipsum. Fusce at rutrum nisl, nec fringilla dolor. In pharetra gravida metus vitae dignissim.</p>
<p>Donec id libero id libero hendrerit placerat. Ut hendrerit bibendum eros, vitae varius arcu ornare id. Nunc elementum, est sed tempus vulputate, lacus nisi vulputate eros, sit amet consequat risus enim et tellus. Sed vel fringilla dolor. Quisque faucibus consequat condimentum. Pellentesque nec elementum purus, a malesuada dui. Aenean sit amet mattis est, a tincidunt quam. Nunc efficitur sollicitudin est, a vulputate mauris imperdiet vel.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec elit mauris, tincidunt a augue quis, elementum luctus magna. Integer egestas ipsum vel condimentum finibus. Pellentesque dui sem, imperdiet vel orci ut, ultrices viverra velit. Aliquam eu neque augue. In quam massa, ornare ut dui a, sollicitudin maximus ipsum. Fusce at rutrum nisl, nec fringilla dolor. In pharetra gravida metus vitae dignissim.</p>

ChuckNorris.Web/Views/Bio/Movies.cshtml
@{
    ViewBag.Title = "Movies";
    Layout = "_Layout";
}

@section Styles {
    <link href="~/css/bio.min.css" rel="stylesheet" asp-append-version="false" />
}

<h1>@ViewBag.Title</h1>

<ul>
    <li>Walker Texas Ranger</li>
    <li>The Expendables</li>
    <li>Enter the Dragon</li>
    <li><a class="chuck-link" href="https://youtu.be/xvmpD4xSSS8?t=1m30s">Conan O'Brien Lever</a></li>
</ul>

<button onclick="window.history.back();">Back</button>

ChuckNorris.Web/Views/Facts/Index.cshtml
@{
    ViewBag.Title = "Facts";
    Layout = "_Layout";
}

@section Styles{
    <link href="~/css/facts.min.css" rel="stylesheet" asp-append-version="false" />
}

@section Scripts{
    <script src="~/js/facts.min.js" asp-append-version="false" defer></script>
}

<h1>@ViewBag.Title</h1>

<aricle id="chuck-facts-area">
    <img id="loader" src="~/images/loader.gif" alt="Loading..." height="100" />
</aricle>

ChuckNorris.Web/Views/Favorites/Index.cshtml
@{
    ViewBag.Title = "Favorites";
    Layout = "_Layout";
}

@section Styles{
    <link href="~/css/favorites.min.css" rel="stylesheet" asp-append-version="false" />
}

@section Scripts{
    <script src="~/js/favorites.min.js" asp-append-version="false" defer></script>
}

<h1>@ViewBag.Title</h1>

<aricle id="chuck-facts-area">
    <img id="loader" src="~/images/loader.gif" alt="Loading..." height="100" />
</aricle>

ChuckNorris.Web/Views/Offline/Index.cshtml
@{
    ViewBag.Title = "Offline";
    Layout = "_Layout";
}

@section Styles {

    <link href="~/css/offline.min.css" rel="stylesheet" asp-append-version="false" />
}

<h1>@ViewBag.Title</h1>
<div class="offline-content">
    <p>Seems like you need to find yourself an internet connection</p>
    <button onclick="window.history.back();">Back</button>
    <img id="offline-dino" src="~/images/offline-dinosaur.gif" alt="offline" />
</div>      

ChuckNorris.Web/Views/Shared/_Layout.cshtml
@inject IConfiguration Configuration

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    @* Meta *@
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="msapplication-TileColor" content="#020b0f">

    @* Manifest Related *@
    <link rel="apple-touch-icon" sizes="180x180" href="~/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon-16x16.png">
    <link rel="manifest" href="~/manifest.json">
    <link rel="mask-icon" href="~/safari-pinned-tab.svg" color="#142234">
    <meta name="msapplication-TileColor" content="#142234">

    @* Style *@
    <link href="~/css/app.min.css" rel="stylesheet" asp-append-version="false" />
    @RenderSection("Styles", required: false)

    @* JS *@
    <script asp-append-version="false" defer>
        const chuckNorrisAppSettings = {
            apiBaseUrl: '@Configuration["apiBaseUrl"]'
        };
    </script>
    <script src="~/vendor/js/jquery-3.3.1.min.js" defer></script>
    <script src="~/js/app.min.js" asp-append-version="false" defer></script>

    @RenderSection("Scripts", required: false)

    @* Title *@
    <title>Chuck Norris [@ViewData["Title"]]</title>
</head>
<body>
    <nav id="main-nav">
        @* Home *@
        <a id="icon-home" asp-controller="Facts" asp-action="Index">
            <img src="~/images/icon-home.png" alt="Home" />
        </a>

        @* Favorites *@
        <a id="icon-favorites" asp-controller="Favorites" asp-action="Index">
            <img src="~/images/icon-favorites.png" alt="Favorite Facts" />
        </a>

        @* Bio *@
        <a id="icon-chuck" asp-controller="Bio" asp-action="Index">
            <img src="~/images/icon-chuck.png" alt="Bio" />
        </a>

        @* Submissions *@
        <a id="icon-contact" asp-controller="Submissions" asp-action="Index">
            <img src="~/images/icon-lightbulb.png" alt="Suggestions" />
        </a>
    </nav>

    <main>
        @RenderBody()
    </main>

    @* Notifications Icon *@
    <div id="notification-icon" class="fixed-icon">
        <img src="~/images/icon-bell.png" alt="Push-ON" asp-append-version="false" />
    </div>

    @* Offline Icon *@
    <div id="offline-icon" class="">
        <img src="~/images/icon-offline.png" alt="Offline" asp-append-version="false" />
    </div>
</body>
</html>

ChuckNorris.Web/Views/Submissions/Index.cshtml
@{
    ViewBag.Title = "Submissions";
    Layout = "_Layout";
}

@section Styles{
    <link href="~/css/submissions.min.css" rel="stylesheet" asp-append-version="false" />
}

@section Scripts{
    <script src="~/js/submissions.min.js" asp-append-version="false" defer></script>
}

<h1>@ViewBag.Title</h1>
<form onsubmit="submitFactForApproval(event)">
    <div id="chuck-cartoon"><img src="~/images/chuck-norris-soldier.png" alt="Chuck Norris" /></div>
    <textarea id="fact-description" maxlength="150"></textarea>
    <div id="submission-controls">
        <button>Submit</button>
        <img id="loader" src="~/images/loader.gif" alt="loading..."/>
    </div>
</form>

<p id="confirmation-area"></p>